include: package:lint/analysis_options.yaml

linter:  
  rules:
    - parameter_assignments

analyzer:
  errors:
    missing_required_param: error
    parameter_assignments: error
    missing_return: error
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false